/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package war.view;

import war.Jogador;
import war.WarControle;

/**
 *
 * @author guest-Rh2WYt
 */
public class PainelControle extends javax.swing.JPanel {

    WarControle warControle = WarControle.getInstance();
    
    /**
     * Creates new form PainelControle
     */
    public PainelControle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDistribucao = new javax.swing.JLabel();
        lbAtaque = new javax.swing.JLabel();
        lbRemanejamento = new javax.swing.JLabel();
        lbNomeJogador = new javax.swing.JLabel();

        lbDistribucao.setText("1. Distribuição");

        lbAtaque.setText("2. Ataque");

        lbRemanejamento.setText("3. Remanejamento");

        lbNomeJogador.setText("nome do jogador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDistribucao)
                    .addComponent(lbNomeJogador)
                    .addComponent(lbAtaque)
                    .addComponent(lbRemanejamento))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeJogador)
                .addGap(94, 94, 94)
                .addComponent(lbDistribucao)
                .addGap(72, 72, 72)
                .addComponent(lbAtaque)
                .addGap(74, 74, 74)
                .addComponent(lbRemanejamento)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void update(Jogador j){
        this.lbNomeJogador.setForeground(j.getColor());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAtaque;
    private javax.swing.JLabel lbDistribucao;
    private javax.swing.JLabel lbNomeJogador;
    private javax.swing.JLabel lbRemanejamento;
    // End of variables declaration//GEN-END:variables
}
